### ISSUE TITLE
 <Icon> is not a valid SSR component.

### ISSUE THREAD

**Issue by dartilesm** [RobBrazier/svelte-awesome#682] opened 2020-09-20 13:58 UTC
Error: Icon is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

**Comment by henriquehbr** [comment] 2021-02-01 21:33
This has already been solved in https://github.com/RobBrazier/svelte-awesome/issues/506

**Comment by benmccann** [comment] 2021-02-04 00:25
Unfortunately, `import Icon from 'svelte-awesome/components/Icon.svelte'` did not work for me in SvelteKit as suggested in #506

**Comment by benmccann** [comment] 2021-02-04 02:59
It looks like this error comes from Svelte core: https://github.com/sveltejs/svelte/blob/ddf13211afcc33f8601133aad9ca270cd1df017f/src/runtime/internal/ssr.ts#L62

**Comment by benmccann** [comment] 2021-02-04 03:22
I see some weird messages inside the compiled component that I suspect may reveal the underlying root cause. There is no `$$render` method available, which is why we're getting this error

```
<Icon> was created without expected prop 'data'
<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'
```

**Comment by student020341** [comment] 2021-02-08 17:52
This worked for me for getting <Icon /> to not err, but I can't get the icons now. 

```
import {refresh} from "svelte-awesome/icons"; // no
import refreshIcon from "svelte-awesome/icons/refresh"; // no
import refreshIcon from "svelte-awesome/icons/refresh.js"; // no
```

But that could be anything, I don't think there is a single library I've been able to npm install and use with sveltekit/snowpack. In this case anyway, I'm getting this error trying to import the icons:

`Error: Import "svelte-awesome/icons/refresh.js" could not be resolved.`

I have been switching between saving this as a regular and dev dependency if that info helps. Using the full Icon.svelte path wasn't fixing the issue if it was a dev dependency.

**Comment by ermos** [comment] 2021-02-17 23:45
SSR component need to access source of the lib, so you need to move the package into dev dependency, after all, you can import your icon like that :
```js
import Icon from 'svelte-awesome';
import {refresh} from 'svelte-awesome/icons';
```
Just tested on a fresh install, it's working.

**Comment by benmccann** [comment] 2021-04-22 06:40
It works for me on the latest SvelteKit now. I don't have to do the Sapper workaround either and can just do `import Icon from 'svelte-awesome';`

**Comment by RobBrazier** [comment] 2021-05-28 17:37
provisionally closing as sapper is deprecated now over sveltekit

**Closed by RobBrazier** 2021-05-28 17:37 UTC
